### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'state_dict'

### ISSUE THREAD

**Issue by khawar-islam** [fistyee/MixPro#3]
Dear @fistyee 

I have followed your installation instruction and after completing one epoch it gives an error.

**Code**

```
loss 6.5611 (6.7661)	grad_norm 2.8034 (nan)	mem 12138MB
[2023-06-08 11:25:02 deit_small_patch14_mask56_224_alpha1](main.py 488): INFO Train: [0/300][4970/5004]	eta 0:00:37 lr 0.000051	time 1.0590 (1.1059)loss 6.6133 (6.7656)	grad_norm 2.9514 (nan)	mem 12138MB
[2023-06-08 11:25:13 deit_small_patch14_mask56_224_alpha1](main.py 488): INFO Train: [0/300][4980/5004]	eta 0:00:26 lr 0.000051	time 1.1264 (1.1059)loss 6.3637 (6.7652)	grad_norm 3.3315 (nan)	mem 12138MB
[2023-06-08 11:25:24 deit_small_patch14_mask56_224_alpha1](main.py 488): INFO Train: [0/300][4990/5004]	eta 0:00:15 lr 0.000051	time 1.0718 (1.1058)loss 6.5798 (6.7649)	grad_norm 2.6179 (nan)	mem 12138MB
[2023-06-08 11:25:35 deit_small_patch14_mask56_224_alpha1](main.py 488): INFO Train: [0/300][5000/5004]	eta 0:00:04 lr 0.000051	time 1.0397 (1.1058)loss 6.7300 (6.7645)	grad_norm 3.6217 (nan)	mem 12138MB
[2023-06-08 11:25:38 deit_small_patch14_mask56_224_alpha1](main.py 497): INFO EPOCH 0 training takes 1:32:13
```

```
Traceback (most recent call last):
  File "main.py", line 645, in <module>
    main(config)
  File "main.py", line 237, in main
    logger,
  File "/home2/coremax/Documents/MixPro/utils.py", line 193, in save_checkpoint
    save_state['amp'] = amp.state_dict()
AttributeError: 'NoneType' object has no attribute 'state_dict'

```

**Comment by fistyee** [comment]
We have fixed this bug in the reversion, please update main.py and utils.py
